version: "3"

services:

  native:
    build: tester/
    command: python -u ./server.py native
    expose:
      - 2001/udp
  
  xml:
    build: tester/
    command: python -u ./server.py xml
    expose:
      - 2002/udp
  
  json:
    build: tester/
    command: python -u ./server.py json
    expose:
      - 2003/udp
  
  protobuf:
    build: tester/
    command: python -u ./server.py protobuf
    expose:
      - 2004/udp
  
  yaml:
    build: tester/
    command: python -u ./server.py yaml
    expose:
      - 2005/udp
  
  msgpack:
    build: tester/
    command: python -u ./server.py msgpack
    expose:
      - 2006/udp
  
  avro:
    build: tester/
    command: python -u ./server.py avro
    expose:
      - 2007/udp
  
  proxy:
    build: proxy/
    expose:
      - 2000/udp
    ports:
      - 2000:2000/udp
    depends_on:
      - native
      - xml
      - json
      - protobuf
      - yaml
      - msgpack
      - avro
